apiVersion: v1
kind: ServiceAccount
metadata:
  name: starlight-deployer
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: starlight-deployer
  namespace: starlight
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: starlight-deployer
  namespace: starlight
subjects:
  - kind: ServiceAccount
    name: starlight-deployer
    namespace: actions-runner-system
roleRef:
  kind: Role
  name: starlight-deployer
  apiGroup: rbac.authorization.k8s.io
