apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: starlight
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 9464
      targetPort: 9464
  selector:
    app: backend
