apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stories-data
  namespace: starlight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
